
services:
  backend:
    build: C:/Users/vgail/Documents/save_food/save_food/back-end  # Remplacez par le chemin vers votre backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development  # Ajustez selon votre environnement

  frontend:
    build: C:/Users/vgail/Documents/save_food/save_food/front-end  # Remplacez par le chemin vers votre frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend